name: Kuber_cluster_monitoring

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check for failed pods
        uses: appleboy/ssh-action@v1.1.0
        with:
          proxy_host: ${{ secrets.JUMPHOST_IP }}
          proxy_port: ${{ secrets.JUMPHOST_PORT }}
          proxy_username: ${{ secrets.JUMPHOST_USER }}
          proxy_password: ${{ secrets.JUMPHOST_PASS }}
          host: ${{ secrets.K9S_SERVER_IP }}
          username: ${{ secrets.K9S_SERVER_USER }}
          password: ${{ secrets.K9S_SERVER_PASS }}
          script: |
            kubectl config use-context k8s --kubeconfig ~/.kube/config-k8s
            kubectl --kubeconfig ~/.kube/config-k8s get pods -A > k8s_status.log
            kubectl config use-context k3s --kubeconfig ~/.kube/config-k3s
            kubectl --kubeconfig ~/.kube/config-k3s get pods -A > k3s_status.log
            grep -E "Error" ~/k3s_status.log ~/k8s_status.log > Monitoring.txt

      - name: Monitoring result download
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          host: ${{ secrets.K9S_SERVER_IP }}
          username: ${{ secrets.K9S_SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          insecure_ignore_fingerprint: true
          proxy_host: ${{ secrets.JUMPHOST_IP }}
          proxy_fingerprint: true
          proxy_username: ${{ secrets.JUMPHOST_USER }}
          proxy_key: ${{ secrets.SSH_KEY }}
          proxy_port: ${{ secrets.JUMPHOST_PORT }}
          insecure_proxy_ignore_fingerprint: true
          source: "/root/Monitoring.txt"
          target: "./Monitoring.txt"    

      - name: Check_Results
        run: |
          cat ./Monitoring.txt
          if grep -q Error ./Monitoring.txt; then
              echo "failed=true" >> $GITHUB_OUTPUT
          else
              echo "failed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Slack Notification on Failure
        if: steps.build.outputs.failed == false
        uses: rtCamp/action-slack-notify@v2   
        env:
          SLACK_COLOR: failure
          SLACK_MESSAGE: "You have some failed pods in your cluster"
          SLACK_TITLE: Kuber Failed Pods
          SLACK_USERNAME: KuberCluster
          SLACK_WEBHOOK: ${{ secrets.HOOK }}
